### ISSUE TITLE
does it work with log4net 1.2.15.0 ?

### ISSUE THREAD

**Issue by KamranShahid** [cjbhaines/Log4Net.Async#27]
does it work with log4net 1.2.15.0 ? My application is logging nothing

**Comment by KamranShahid** [comment]
Nobody is looking after this repository anymore?

**Comment by KamranShahid** [comment]
I were able to log after i compile Log4Net.Async dll with newer version of log4net and then adding <lockingModel type="log4net.Appender.FileAppender+MinimalLock" /> in my rolling file appender
Thanks

**Comment by cjbhaines** [comment]
Log4Net.Async is compiled against NuGet package 2.0.3 (1.2.13.0) and the latest package is 2.0.5 (version 1.2.15.0). As long as there are no breaking changes in their API (which there won't be because they didn't bump the major version) it will work fine. I've just run the tests against 2.0.5 and it works fine suggesting it works.

The logs should be written instantly to the log file assuming you are not calling Log faster than the appender can keep up with. What exactly were you expecting?

**Comment by KamranShahid** [comment]
Actually by buffersize my thinking were that it will store till 200 entries somewhere in memory. then will output to the file. That's how there will be less I/O and might be a performance gain. Like adonetappender buffersize property.
About version I will have to check again what nugetpackage i have downloaded a month or so ago.

**Comment by rcollette** [comment]
@KamranShahid - What you are referring to is BufferringForwardingAppender.  See:
https://logging.apache.org/log4net/release/config-examples.html

This can be used with other appenders, including this one.   There is no need to re-implement that behavior in these appenders.

**Comment by cjbhaines** [comment]
@KamranShahid, as Richard says this is not the intention of this library. The forwarders will write to the underlying appenders as fast as they can, using only a single thread to do so. This library is used to speed up calling code that needs to log so that it does not have to wait for things like file access, database access, etc.

**Comment by KamranShahid** [comment]
Acknowledged Richard and Chris.
